### ISSUE TITLE
Initial Sphinx Documentation

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-ops#10]
Priority number 1. Documentation target for this issue should be enough to onboard a new qhub user and detail the steps:

    Initial deployment on aws and digital ocean
    Day to day maintenance tasks
        update environment image
        increasing/decreasing node limits for dask workers
    Architecture overview
    Why design decisions were made

**Comment by prasunanand** [comment]
Do we need a sphinx documentation ?

**Comment by costrouc** [comment]
Sphinx documentation in `qhub` repository
