### ISSUE TITLE
Error creating conda environment in home directory

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-ops#17]
```
jovyan@jupyter-t-2dpotts:~$ conda install -c conda-forge awscli -y
Collecting package metadata (current_repodata.json): failedNotWritableError: The current user does not have write permissions to a required path.
  path: /opt/conda/pkgs/urls.txt
  uid: 1000
  gid: 0If you feel that permissions on this path are set incorrectly, you can manually
change them by executing  $ sudo chown 1000:0 /opt/conda/pkgs/urls.txt
```

Reported by @t-potts

**Comment by tylerpotts** [comment]
For the other deployments we've named the environment where we have all the packages installed `default`. I think we would want to do the same thing here since some of our API is written with this in mind

Also, the default terminal is `sh`, I think it should be `bash`

**Comment by costrouc** [comment]
Fixed in latest qhub ops deployment. Will propagate to datum deployment and close issue once we can demonstrate it works for you.
