### ISSUE TITLE
Error on build for Datum GCP deployment

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-ops#19]
When I tried to add a package to the Datum GCP deployment for the first time I got this error in the github actions:

```bash
##[error]Process completed with exit code 2.
Run docker build -f "image/Dockerfile." -t $IMAGE_NAME:$IMAGE_TAG" image
/home/runner/work/_temp/12b6d741-061a-476a-80ce-492469735078.sh: line 1: unexpected EOF while looking for matching `"'
##[error]Process completed with exit code 2.
```

**Comment by tylerpotts** [comment]
Here's the run ID:
https://github.com/Quansight/qhub-deployments-datum-gcp-qhub/pull/2/checks?check_run_id=643247187

And here's the associated PR:
https://github.com/Quansight/qhub-deployments-datum-gcp-qhub/pull/2

**Comment by costrouc** [comment]
Error looks to be resolved. It was due to the template for image-pr being incorrect this commit https://github.com/Quansight/qhub-ops/commit/d9ca9df4f6bf798acc0ec9a8061f9c24eab04895 addresses the issue. Closing as now resolved.
