### ISSUE TITLE
FAQ Questions and notes on QHub github pages

### ISSUE THREAD

**Issue by tonyfast** [Quansight/qhub-ops#44]
Notes from a call with @anirrudh 

* Main Links 
  * Document, Blog, FAQ, Github, DockerHub
* Copy
  > This is Qhub
  > Your Jupyter infrastructure as code.
  > Curated by open source experts at Quansight.
* FAQ
  * What challenges does Qhub fix?
  * What technologies does QHub rely on?
    * What is Jupyter?
    * what is Dask
  * What are environments? This term is used a few different ways terraform, conda, docker, dask.
  * Why open source?
  * What parts are not open source?
  * QHub vs JupyterHub
  * Ask an expert -> go to github issues

**Comment by anirrudh** [comment]
Notes from call with @tonyfast , @ftarlaci 

* Kubernates vs Docker - how to explain them/ to what depth to explain them?
* one-line sentence for the Qhub stuff
* Nikola baked-in to JupyterLab

**Comment by anirrudh** [comment]
@tonyfast, let's also use this as a page to (eventually) have a design discussion about FAQs

**Comment by tonyfast** [comment]
we got this done

faq in the docs
