### ISSUE TITLE
Integrate jupyter-videochat into qhub by default

### ISSUE THREAD

**Issue by yuvipanda** [Quansight/qhub-ops#53]
To help with trainings, etc, we want [jupyter-videochat](https://github.com/yuvipanda/jupyter-videochat) installed by default. It becomes a JupyterLab extension enabled by default and provided on the right sidebar.

**Comment by costrouc** [comment]
@yuvipanda I have this added to the latest qhub deployment but for some reason I am unable to "join room by name". Am I missing something in the configuration?

**Comment by yuvipanda** [comment]
@costrouc can you tell me what version of jupyterlab-videochat is installed? Also does it show the hardcoded 'CA 16A' style room names?

**Comment by costrouc** [comment]
Version

![image](https://user-images.githubusercontent.com/1740337/86256463-5b4ce800-bb86-11ea-8ffb-a59eb564f322.png)

This is the screen I see with no default chats

![image](https://user-images.githubusercontent.com/1740337/86256559-77508980-bb86-11ea-99de-963001cf2b68.png)
